# ==========================================
# VERSION CONTROL - MundoGo Orchestrator
# ==========================================
VERSION_MAJOR = 2
VERSION_MINOR = 16
VERSION_PATCH = 1
VERSION_STRING = f"v{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}"
VERSION_TYPE = "major" if VERSION_MAJOR > 0 else "minor"

def get_version():
    return VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, VERSION_STRING, VERSION_TYPE

def bump_patch():
    global VERSION_PATCH, VERSION_STRING
    VERSION_PATCH += 1
    VERSION_STRING = f"v{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}"
    return VERSION_STRING

def bump_minor():
    global VERSION_MINOR, VERSION_PATCH, VERSION_STRING, VERSION_TYPE
    VERSION_MINOR += 1
    VERSION_PATCH = 1
    VERSION_STRING = f"v{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}"
    VERSION_TYPE = "major" if VERSION_MAJOR > 0 else "minor"
    return VERSION_STRING

def bump_major():
    global VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, VERSION_STRING, VERSION_TYPE
    VERSION_MAJOR += 1
    VERSION_MINOR = 0
    VERSION_PATCH = 1
    VERSION_STRING = f"v{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}"
    VERSION_TYPE = "major"
    return VERSION_STRING
